controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController


joint_state_broadcaster:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint

diff_drive_controller:
  ros__parameters:
    # use_stamped_vel: false # depricated from jazzy
    publish_rate: 50.0
    base_frame_id: base_footprint
    enable_odom_tf: true # jazzy default true, change it to true when using all the hardwares
    odom_frame_id: odom
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.33   
    wheel_radius: 0.045       
    
    # Odometry
    enable_odom_tf: true
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    # Command timeout
    cmd_vel_timeout: 0.5
    
    # Publishing
    publish_limited_velocity: true
    velocity_rolling_window_size: 10
